// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package configmap1980

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(in *jlexer.Lexer, out *TorServer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pod_name":
			out.PodName = string(in.String())
		case "server_id":
			out.ServerId = string(in.String())
		case "device":
			if in.IsNull() {
				in.Skip()
				out.Device = nil
			} else {
				in.Delim('[')
				if out.Device == nil {
					if !in.IsDelim(']') {
						out.Device = make([]TorDevice, 0, 0)
					} else {
						out.Device = []TorDevice{}
					}
				} else {
					out.Device = (out.Device)[:0]
				}
				for !in.IsDelim(']') {
					var v1 TorDevice
					(v1).UnmarshalEasyJSON(in)
					out.Device = append(out.Device, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(out *jwriter.Writer, in TorServer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pod_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.PodName))
	}
	{
		const prefix string = ",\"server_id\":"
		out.RawString(prefix)
		out.String(string(in.ServerId))
	}
	{
		const prefix string = ",\"device\":"
		out.RawString(prefix)
		if in.Device == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Device {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TorServer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TorServer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TorServer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TorServer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap1980(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(in *jlexer.Lexer, out *TorList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "server_count":
			out.ServerCount = string(in.String())
		case "server_list":
			if in.IsNull() {
				in.Skip()
				out.ServerList = nil
			} else {
				in.Delim('[')
				if out.ServerList == nil {
					if !in.IsDelim(']') {
						out.ServerList = make([]TorServer, 0, 1)
					} else {
						out.ServerList = []TorServer{}
					}
				} else {
					out.ServerList = (out.ServerList)[:0]
				}
				for !in.IsDelim(']') {
					var v4 TorServer
					(v4).UnmarshalEasyJSON(in)
					out.ServerList = append(out.ServerList, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(out *jwriter.Writer, in TorList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	{
		const prefix string = ",\"server_count\":"
		out.RawString(prefix)
		out.String(string(in.ServerCount))
	}
	{
		const prefix string = ",\"server_list\":"
		out.RawString(prefix)
		if in.ServerList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.ServerList {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TorList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TorList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TorList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TorList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19801(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(in *jlexer.Lexer, out *TorDevice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "device_id":
			out.DeviceId = string(in.String())
		case "device_ip":
			out.DeviceIp = string(in.String())
		case "rank_id":
			out.RankId = string(in.String())
		case "tor_ip":
			out.TorIp = string(in.String())
		case "tor_port":
			out.TorPort = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(out *jwriter.Writer, in TorDevice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"device_ip\":"
		out.RawString(prefix)
		out.String(string(in.DeviceIp))
	}
	{
		const prefix string = ",\"rank_id\":"
		out.RawString(prefix)
		out.String(string(in.RankId))
	}
	{
		const prefix string = ",\"tor_ip\":"
		out.RawString(prefix)
		out.String(string(in.TorIp))
	}
	{
		const prefix string = ",\"tor_port\":"
		out.RawString(prefix)
		out.String(string(in.TorPort))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TorDevice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TorDevice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TorDevice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TorDevice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19802(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(in *jlexer.Lexer, out *SuperPodServer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "server_id":
			out.ServerId = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(out *jwriter.Writer, in SuperPodServer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"server_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServerId))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SuperPodServer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SuperPodServer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SuperPodServer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SuperPodServer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19803(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(in *jlexer.Lexer, out *SuperPodBase) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "super_pod_id":
			out.SuperPodId = string(in.String())
		case "server_list":
			if in.IsNull() {
				in.Skip()
				out.ServerList = nil
			} else {
				in.Delim('[')
				if out.ServerList == nil {
					if !in.IsDelim(']') {
						out.ServerList = make([]SuperPodServer, 0, 4)
					} else {
						out.ServerList = []SuperPodServer{}
					}
				} else {
					out.ServerList = (out.ServerList)[:0]
				}
				for !in.IsDelim(']') {
					var v7 SuperPodServer
					(v7).UnmarshalEasyJSON(in)
					out.ServerList = append(out.ServerList, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(out *jwriter.Writer, in SuperPodBase) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"super_pod_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.SuperPodId))
	}
	{
		const prefix string = ",\"server_list\":"
		out.RawString(prefix)
		if in.ServerList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.ServerList {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SuperPodBase) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SuperPodBase) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SuperPodBase) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SuperPodBase) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19804(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(in *jlexer.Lexer, out *ServerBase) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "server_id":
			out.ServerId = string(in.String())
		case "device":
			if in.IsNull() {
				in.Skip()
				out.Device = nil
			} else {
				in.Delim('[')
				if out.Device == nil {
					if !in.IsDelim(']') {
						out.Device = make([]DeviceBase, 0, 0)
					} else {
						out.Device = []DeviceBase{}
					}
				} else {
					out.Device = (out.Device)[:0]
				}
				for !in.IsDelim(']') {
					var v10 DeviceBase
					(v10).UnmarshalEasyJSON(in)
					out.Device = append(out.Device, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(out *jwriter.Writer, in ServerBase) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"server_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ServerId))
	}
	{
		const prefix string = ",\"device\":"
		out.RawString(prefix)
		if in.Device == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Device {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ServerBase) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ServerBase) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ServerBase) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ServerBase) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19805(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(in *jlexer.Lexer, out *RankTable) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "version":
			out.Version = string(in.String())
		case "data_Version":
			out.DataVersion = int(in.Int())
		case "server_count":
			out.ServerCount = string(in.String())
		case "server_list":
			if in.IsNull() {
				in.Skip()
				out.ServerList = nil
			} else {
				in.Delim('[')
				if out.ServerList == nil {
					if !in.IsDelim(']') {
						out.ServerList = make([]ServerBase, 0, 1)
					} else {
						out.ServerList = []ServerBase{}
					}
				} else {
					out.ServerList = (out.ServerList)[:0]
				}
				for !in.IsDelim(']') {
					var v13 ServerBase
					(v13).UnmarshalEasyJSON(in)
					out.ServerList = append(out.ServerList, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "super_pod_list":
			if in.IsNull() {
				in.Skip()
				out.SuperPodList = nil
			} else {
				in.Delim('[')
				if out.SuperPodList == nil {
					if !in.IsDelim(']') {
						out.SuperPodList = make([]SuperPodBase, 0, 1)
					} else {
						out.SuperPodList = []SuperPodBase{}
					}
				} else {
					out.SuperPodList = (out.SuperPodList)[:0]
				}
				for !in.IsDelim(']') {
					var v14 SuperPodBase
					(v14).UnmarshalEasyJSON(in)
					out.SuperPodList = append(out.SuperPodList, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(out *jwriter.Writer, in RankTable) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.String(string(in.Version))
	}
	if in.DataVersion != 0 {
		const prefix string = ",\"data_Version\":"
		out.RawString(prefix)
		out.Int(int(in.DataVersion))
	}
	{
		const prefix string = ",\"server_count\":"
		out.RawString(prefix)
		out.String(string(in.ServerCount))
	}
	{
		const prefix string = ",\"server_list\":"
		out.RawString(prefix)
		if in.ServerList == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v15, v16 := range in.ServerList {
				if v15 > 0 {
					out.RawByte(',')
				}
				(v16).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.SuperPodList) != 0 {
		const prefix string = ",\"super_pod_list\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v17, v18 := range in.SuperPodList {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RankTable) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RankTable) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RankTable) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RankTable) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19806(l, v)
}
func easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(in *jlexer.Lexer, out *DeviceBase) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "device_id":
			out.DeviceId = string(in.String())
		case "super_device_id":
			out.SuperDeviceId = string(in.String())
		case "device_ip":
			out.DeviceIp = string(in.String())
		case "rank_id":
			out.RankId = string(in.String())
		case "tor_ip":
			out.TorIp = string(in.String())
		case "tor_port":
			out.TorPort = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(out *jwriter.Writer, in DeviceBase) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	if in.SuperDeviceId != "" {
		const prefix string = ",\"super_device_id\":"
		out.RawString(prefix)
		out.String(string(in.SuperDeviceId))
	}
	{
		const prefix string = ",\"device_ip\":"
		out.RawString(prefix)
		out.String(string(in.DeviceIp))
	}
	{
		const prefix string = ",\"rank_id\":"
		out.RawString(prefix)
		out.String(string(in.RankId))
	}
	if in.TorIp != "" {
		const prefix string = ",\"tor_ip\":"
		out.RawString(prefix)
		out.String(string(in.TorIp))
	}
	if in.TorPort != "" {
		const prefix string = ",\"tor_port\":"
		out.RawString(prefix)
		out.String(string(in.TorPort))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeviceBase) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeviceBase) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonFc190f7cEncodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeviceBase) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeviceBase) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonFc190f7cDecodeVolcanoShVolcanoPkgUtilPluginsConfigmap19807(l, v)
}
