// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ringcontroller

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller(in *jlexer.Lexer, out *TorDevice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "device_id":
			out.DeviceId = string(in.String())
		case "device_ip":
			out.DeviceIp = string(in.String())
		case "rank_id":
			out.RankId = string(in.String())
		case "tor_ip":
			out.TorIp = string(in.String())
		case "tor_port":
			out.TorPort = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller(out *jwriter.Writer, in TorDevice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	{
		const prefix string = ",\"device_ip\":"
		out.RawString(prefix)
		out.String(string(in.DeviceIp))
	}
	{
		const prefix string = ",\"rank_id\":"
		out.RawString(prefix)
		out.String(string(in.RankId))
	}
	{
		const prefix string = ",\"tor_ip\":"
		out.RawString(prefix)
		out.String(string(in.TorIp))
	}
	{
		const prefix string = ",\"tor_port\":"
		out.RawString(prefix)
		out.String(string(in.TorPort))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TorDevice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TorDevice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TorDevice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TorDevice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller(l, v)
}
func easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller1(in *jlexer.Lexer, out *PodTorInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pod_name":
			out.PodName = string(in.String())
		case "server_id":
			out.ServerId = string(in.String())
		case "device":
			if in.IsNull() {
				in.Skip()
				out.Devices = nil
			} else {
				in.Delim('[')
				if out.Devices == nil {
					if !in.IsDelim(']') {
						out.Devices = make([]TorDevice, 0, 0)
					} else {
						out.Devices = []TorDevice{}
					}
				} else {
					out.Devices = (out.Devices)[:0]
				}
				for !in.IsDelim(']') {
					var v1 TorDevice
					(v1).UnmarshalEasyJSON(in)
					out.Devices = append(out.Devices, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller1(out *jwriter.Writer, in PodTorInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pod_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.PodName))
	}
	{
		const prefix string = ",\"server_id\":"
		out.RawString(prefix)
		out.String(string(in.ServerId))
	}
	{
		const prefix string = ",\"device\":"
		out.RawString(prefix)
		if in.Devices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Devices {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PodTorInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PodTorInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PodTorInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PodTorInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller1(l, v)
}
func easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller2(in *jlexer.Lexer, out *PodNpuInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "pod_name":
			out.PodName = string(in.String())
		case "server_id":
			out.ServerId = string(in.String())
		case "devices":
			if in.IsNull() {
				in.Skip()
				out.Devices = nil
			} else {
				in.Delim('[')
				if out.Devices == nil {
					if !in.IsDelim(']') {
						out.Devices = make([]NpuDevice, 0, 0)
					} else {
						out.Devices = []NpuDevice{}
					}
				} else {
					out.Devices = (out.Devices)[:0]
				}
				for !in.IsDelim(']') {
					var v4 NpuDevice
					(v4).UnmarshalEasyJSON(in)
					out.Devices = append(out.Devices, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller2(out *jwriter.Writer, in PodNpuInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"pod_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.PodName))
	}
	{
		const prefix string = ",\"server_id\":"
		out.RawString(prefix)
		out.String(string(in.ServerId))
	}
	{
		const prefix string = ",\"devices\":"
		out.RawString(prefix)
		if in.Devices == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Devices {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PodNpuInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PodNpuInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PodNpuInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PodNpuInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller2(l, v)
}
func easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller3(in *jlexer.Lexer, out *NpuDevice) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "device_id":
			out.DeviceId = string(in.String())
		case "super_device_id":
			out.SuperDeviceId = string(in.String())
		case "device_ip":
			out.DeviceIp = string(in.String())
		case "tor_ip":
			out.TorIp = string(in.String())
		case "tor_port":
			out.TorPort = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller3(out *jwriter.Writer, in NpuDevice) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"device_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.DeviceId))
	}
	if in.SuperDeviceId != "" {
		const prefix string = ",\"super_device_id\":"
		out.RawString(prefix)
		out.String(string(in.SuperDeviceId))
	}
	{
		const prefix string = ",\"device_ip\":"
		out.RawString(prefix)
		out.String(string(in.DeviceIp))
	}
	if in.TorIp != "" {
		const prefix string = ",\"tor_ip\":"
		out.RawString(prefix)
		out.String(string(in.TorIp))
	}
	if in.TorPort != "" {
		const prefix string = ",\"tor_port\":"
		out.RawString(prefix)
		out.String(string(in.TorPort))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NpuDevice) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NpuDevice) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson84654fb2EncodeVolcanoShVolcanoPkgControllersRingcontroller3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NpuDevice) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NpuDevice) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson84654fb2DecodeVolcanoShVolcanoPkgControllersRingcontroller3(l, v)
}
